In [1]:
# importing numpy library
import numpy as np

In [39]:
# Creating Support Vector Classifier

class SVM_classifier():


  # initiating the hyperparameters
  def __init__(self, learning_rate, no_of_iterations, lambda_parameter):

    self.learning_rate = learning_rate
    self.no_of_iterations = no_of_iterations
    self.lambda_parameter = lambda_parameter


  
  # fitting the dataset to SVM Classifier
  def fit(self, X, Y):

    # m  --> number of Data points --> number of rows
    # n  --> number of input features --> number of columns
    self.m, self.n = X.shape

    # initiating the weight value and bias value

    self.w = np.zeros((self.n,1))

    self.b = 0

    self.X = X

    self.Y = Y

    # implementing Gradient Descent algorithm for Optimization

    for i in range(self.no_of_iterations):
      self.update_weights()

    return self.w,self.b

  # function for updating the weight and bias value
  def update_weights(self):

    # label encoding
    # Encoding all negative values to -1 and all positive values to 1
    y_label = np.where(self.Y <= 0, -1, 1)


    # gradients ( dw, db)
    for index, x_i in enumerate(self.X):

      condition = y_label[index] * (np.dot(x_i, self.w) - self.b) >= 1

      if (condition.all() == True):

        dw = 2 * self.lambda_parameter * self.w
        db = 0

      else:
        
        dw = 2 * self.lambda_parameter * self.w - np.dot(x_i.T.reshape(-1,1), y_label[index].reshape((1,1)))
        
        db = y_label[index]


      self.w = self.w - self.learning_rate * dw

      self.b = self.b - self.learning_rate * db



  # predict the label for a given input value
  def predict(self, X):

    output = np.dot(X, self.w) - self.b
    
    predicted_labels = np.sign(output)

    y_hat = np.where(predicted_labels <= -1, 0, 1)

    return y_hat

In [40]:
TrainData=np.loadtxt("TrainDataForDiabetes.csv",delimiter=",",skiprows=1)

In [41]:
TestData=np.loadtxt("TestDataForDiabetes.csv",delimiter=",",skiprows=1)

In [42]:
XTrain=TrainData[:, :-1]
YTrain=TrainData[:, -1].reshape((-1,1))
XTest=TestData[:, :-1]
YTest=TestData[:, -1].reshape((-1,1))

In [43]:
print(XTrain.shape)
print(YTrain.shape)
print(XTest.shape)
print(YTest.shape)

(80, 8)
(80, 1)
(20, 8)
(20, 1)


In [44]:
model=SVM_classifier(0.001,1000,0.01)

In [49]:
model.fit(XTrain,YTrain)

(array([[ 1.04944702],
        [-0.0368152 ],
        [-0.29125526],
        [ 0.1539854 ],
        [-0.11506687],
        [ 0.20613476],
        [ 1.03607757],
        [ 0.12804588]]),
 array([2.935]))

In [65]:
OurPredictionsOnTestDataSet=model.predict(XTest)
OurPredictionsOnTestDataSet

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])