In [317]:
# For creating random arrays and performing numeriacl computaions on multidimensional arrays
import numpy as np

# To view multidimensional array in dataframe format
import pandas as pd

In [318]:

NoofFeatures = 8
NoofSamples = 150
data = np.random.rand(NoofSamples, NoofFeatures)
data

array([[0.91153695, 0.74896568, 0.55172731, ..., 0.69124928, 0.71237749,
        0.26466663],
       [0.90345003, 0.62656029, 0.161987  , ..., 0.23525497, 0.23022878,
        0.24847568],
       [0.32503713, 0.92074913, 0.82782639, ..., 0.84472987, 0.31730537,
        0.52223294],
       ...,
       [0.72527784, 0.42560411, 0.54217385, ..., 0.77551069, 0.3155721 ,
        0.56382826],
       [0.99051797, 0.52477399, 0.32687042, ..., 0.13255607, 0.03791067,
        0.0421957 ],
       [0.34602463, 0.27675626, 0.95691605, ..., 0.54504555, 0.55575379,
        0.64034364]])

In [319]:
labels = np.random.choice([0, 1], NoofSamples).reshape(-1, 1)
labels

array([[1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
    

In [320]:
data = np.hstack((data, labels))
data

array([[0.91153695, 0.74896568, 0.55172731, ..., 0.71237749, 0.26466663,
        1.        ],
       [0.90345003, 0.62656029, 0.161987  , ..., 0.23022878, 0.24847568,
        1.        ],
       [0.32503713, 0.92074913, 0.82782639, ..., 0.31730537, 0.52223294,
        0.        ],
       ...,
       [0.72527784, 0.42560411, 0.54217385, ..., 0.3155721 , 0.56382826,
        0.        ],
       [0.99051797, 0.52477399, 0.32687042, ..., 0.03791067, 0.0421957 ,
        1.        ],
       [0.34602463, 0.27675626, 0.95691605, ..., 0.55575379, 0.64034364,
        0.        ]])

In [321]:
DataFrame = pd.DataFrame(data, columns = ["column1", "column2", "column3", "column4", "column5", "column6", "column7"
                                         , "column8", "Target"])
DataFrame

column1   column2   column3   column4   column5   column6   column7  \
0    0.911537  0.748966  0.551727  0.210204  0.916817  0.691249  0.712377   
1    0.903450  0.626560  0.161987  0.772146  0.615695  0.235255  0.230229   
2    0.325037  0.920749  0.827826  0.076615  0.128831  0.844730  0.317305   
3    0.054053  0.071210  0.299820  0.126293  0.819635  0.164257  0.964131   
4    0.585186  0.798749  0.828683  0.603726  0.945621  0.158726  0.541716   
..        ...       ...       ...       ...       ...       ...       ...   
145  0.421247  0.833867  0.447115  0.673604  0.545643  0.183373  0.111910   
146  0.313534  0.491613  0.188965  0.190566  0.172941  0.737589  0.704118   
147  0.725278  0.425604  0.542174  0.259065  0.194146  0.775511  0.315572   
148  0.990518  0.524774  0.326870  0.469361  0.464787  0.132556  0.037911   
149  0.346025  0.276756  0.956916  0.268366  0.760525  0.545046  0.555754   

      column8  Target  
0    0.264667     1.0  
1    0.248476     1.0  
2    0.522233     0.0  
3    0.375068     0.0  
4    0.971482     0.0  
..        ...     ...  
145  0.818577     1.0  
146  0.261818     1.0  
147  0.563828     0.0  
148  0.042196     1.0  
149  0.640344     0.0  

[150 rows x 9 columns]

In [322]:
# We can't perform tests on train data itself
# if we do that, then our model gets overfitted
# means it performs well on already visited data, but predicts bad for unseen data
# to tackle this we have different methods in model evalution

# Different types of techniques in Model Evalution
# Hold Out
# Cross Validation

# Hold Out

# In hold out we devide dataset into three subsets
# 1. Train Dataset
# 2. Validation Dataset
# 3. Test Dataset

# Each dataset is subset of dataset, observations in each dataset are unique (if we done data preparaion properly)
# In this method of model evalution, we train the model on train dataset(it may be 70%)
# we do the validation process, to get best hyperparameters for the given dataset and model
# Note all models may not this validation subset for model evalution (may be 15% if  needed)
# We test the model on test dataset, to track feature performance of our model

# Hold out model evalution using numpy

TrianSplitPercentage = 70
ValidationSplitPercentage = 15
TestSplitPercentage = 15

# First let us find percentage of positive's and negative's in our dataset
NoofPositives = DataFrame[DataFrame["Target"] == 1].shape[0]

# We have 74 1's and 76 0's in out dataset
ProbabilityOfPositivesInDF = NoofPositives/(NoofSamples)

# We don't need to calculate probability for negatives
# We can get it by positive probalbility from total probability(1)

# NoofNegatives = DataFrame[DataFrame["Target"] == 0].shape[0]


In [323]:
# We can devide df into three subsets, without considering amount of negatives and positives in our dataset
# If we do that, there are chances of getting all one's or zero's in any of three subsets
# Or atleast there are chances of getting more zero's, less one's and viceversa

# Therefore applying stratified way of splitting can become crucial in model performace
# Below is the stratified way of spltting dataset using hold out model evalution method

# np.random.shuffle(data)

HoldOutTrainSampleSize = int((TrianSplitPercentage/100) * NoofSamples)
HoldOutValSamplesSize = int((ValidationSplitPercentage/100) * NoofSamples)
HoldOutTestSize = int((TestSplitPercentage/100) * NoofSamples)

# print(HoldOutTrainSampleSize)
# print(HoldOutValSamplesSize)
# print(HoldOutTestSize)


# Initilizing and declaring datasets as empty using np.empty

HoldOutTrain = np.empty((HoldOutTrainSampleSize, NoofFeatures+1))
HoldOutVal = np.empty((HoldOutValSamplesSize, NoofFeatures+1))
HoldOutTest = np.empty((HoldOutTestSize, NoofFeatures+1))


# Get correct split of positives and negatives, depending on one's and zero's probability in our dataset
LabelsForHoldOutTrainSet = np.random.choice([1, 0], HoldOutTrainSampleSize, p = [ProbabilityOfPositivesInDF, 1 - ProbabilityOfPositivesInDF])

# print(vals)

for i in range(LabelsForHoldOutTrainSet.size):
    
    # To get first occurance of label, we use np.where
    # but it returns all indexes with that the label specified
    indexes = np.where(data[:, -1] == LabelsForHoldOutTrainSet[i])
    
    # So we get first occurance of label by using indexes[0][0] # means [first row][first column]
    # since it is multidimensional array we use [0][0] instead of [0]
    FirstOccurance = indexes[0][0]
    
    # Update values in HoldOutTrain that we declared as an empty array before
    HoldOutTrain[i] =  data[index, :]
    
    # Now delete the sample in original dataframe
    data = np.delete(data, index, axis = 0)

In [324]:
# Numpy array to DataFrame
HoldOutTrainData = pd.DataFrame(HoldOutTrain, columns=["column1", "column2", "column3", "column4", "column5", "column6", "column7"
                                         , "column8", "Target"])

In [325]:
# Generating validation subset whose size is 15% of parent set

# Find probabilities of positives and negatives in the remaining data
DataFrame = pd.DataFrame(data, columns=["column1", "column2", "column3", "column4", "column5", "column6", "column7"
                                         , "column8", "Target"])

ProbabilityOfPositives = DataFrame[DataFrame["Target"] == 1].shape[0]/ DataFrame.shape[0]
ProbabilityOfPositives

# Negative's probability in latest dataset is 1 - ProbabilityOfPositives

0.4888888888888889

In [326]:
# Get correct split of positives and negatives for hold out validation subset
# depending on one's and zero's probability in remain dataset
LabelsForHoldOutValSet = np.random.choice([1, 0], HoldOutValSamplesSize, 
                                          p = [ProbabilityOfPositives, 1 - ProbabilityOfPositives])


for i in range(LabelsForHoldOutValSet.size):
    
    # getting indexes of DataFrame where target is current label
    indexes = np.where(data[:, -1] == LabelsForHoldOutValSet[i])
    
    # Get first index from indexes
    FirstOccurance = indexes[0][0]
    
    # Update values in HoldOutVal
    HoldOutVal[i] = data[FirstOccurance, :]
    
    # Delete sample by index in data
    data = np.delete(data, index, axis = 0)

In [327]:
# Creating dataframe for holdoutval set
HoldOutValData = pd.DataFrame(HoldOutVal, columns = ["column1", "column2", "column3", "column4", "column5", "column6", "column7"
                                         , "column8", "Target"])

In [328]:
# Remaining samples in data are actually test data
# therefore we can consider this as test dataset
HoldOutTestData = pd.DataFrame(data, columns = ["column1", "column2", "column3", "column4", "column5", "column6", "column7"
                                         , "column8", "Target"])

In [329]:
# Let us view what we get from above traintest split procedure
# TrainSet

print("Actual Data")
print("No of Positive labels : ", NoofPositives)
print("No of Negative labels : ", NoofSamples - NoofPositives)

# No of positives in train data
NoofPos = HoldOutTrainData[HoldOutTrainData["Target"] == 0].shape[0]

print("Train Data")
print("No of Positive labels : ",NoofPos)

# No of negatives in train data
print("No of Positive labels : ",HoldOutTrainData.shape[0] - NoofPos)

# No of positives in Validation set
NoofPos = HoldOutValData[HoldOutValData["Target"] == 0].shape[0]

print("Validation Data")

print("No of Positive labels : ",NoofPos)

# No of negative labels in validation data
print("No of Negative labels : ",HoldOutValData.shape[0] - NoofPos)

print("Test Data")

# No of positives in Test set
NoofPos = HoldOutTestData[HoldOutTestData["Target"] == 0].shape[0]

print("No of Positive labels : ",NoofPos)

# No of negatives
print("No of Positive labels : ",HoldOutTestData.shape[0] - NoofPos)

Actual Data
No of Positive labels :  72
No of Negative labels :  78
Train Data
No of Positive labels :  55
No of Positive labels :  50
Validation Data
No of Positive labels :  12
No of Negative labels :  10
Test Data
No of Positive labels :  14
No of Positive labels :  9


In [335]:
print(HoldOutTrainData.iloc[:, -1].values)
print(HoldOutValData.iloc[:, -1].values)
print(HoldOutTestData.iloc[:, -1].values, end = "\n\n")

# It is stratified way of sampling, after splitting there same amount(a little bit vary) of 
# negatives and positives in each subset.
# Will upload all cross validation techniques as a seperate file
# let me know if any updates or errors or better way of doing(not sklearn)

[1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 1. 1. 1. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 0.
 0. 0. 1. 0. 1. 1. 0. 0. 0. 1. 1. 0. 1. 0. 1. 1. 0. 1. 1. 0. 0. 1. 1. 1.
 0. 0. 0. 1. 0. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1.
 1. 1. 1. 1. 0. 0. 0. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0.
 1. 1. 1. 0. 1. 0. 1. 0. 0.]
[1. 0. 1. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 1. 1. 1. 1. 0. 0. 1.]
[0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 0. 0. 0. 1. 1. 0. 1. 0.]

